export const STRINGS = {
  fa: {
    save: 'ذخیره',
    gallery: 'گالری',
    donate: 'حمایت مالی',
    settings: 'تنظیمات',
    undo: 'برگردان',
    redo: 'انجام دوباره',
    placeholder: 'اینجا بنویسید…',
    clear: 'پاک کردن',
    tabFont: 'فونت',
    tabStyle: 'استایل',
    tabBox: 'جعبه متن',
    boxCustomize: 'تنظیمات جعبه متن',
    boxBgColor: 'رنگ زمینه جعبه',
    boxOpacity: 'شفافیت جعبه',
    boxRadius: 'گردی گوشه‌ها',
    boxPadding: 'فاصله داخلی',
    boxReset: 'حالت پیش‌فرض این استایل',
    tabColor: 'رنگ متن',
    tabBg: 'پس‌زمینه',
    tabLayout: 'چیدمان',
    tabMagic: 'جادویی',
    tabTemplates: 'قالب‌ها',
    yourFont: 'فونت خودت',
    effect: 'افکت و استایل متن',
    fx_none: 'بدون افکت',
    fx_neon: 'نئون سایبر',
    fx_gradient: 'گرادیان زنده',
    fx_pop3d: 'سه‌بعدی ۳D',
    fx_glitch: 'گلیچ دیجیتال',
    fx_retro: 'پاپ‌آرت رترو',
    fx_softBloom: 'درخشش رویایی',
    fx_emboss: 'برجسته / پِرِس',
    fx_glass: 'شیشه‌ای لکوئید',
    fx_outline: 'توخالی مدرن',
    fx_fire: 'آتشین و گدازه',
    fx_duoStroke: 'کانتور دوگانه',
    fx_chrome: 'کروم طلایی',
    fx_shadowCast: 'سایه سینمایی',
    fxCustomize: 'تنظیمات افکت متن',
    fxColor: 'رنگ افکت / هاله',
    fxGradientSelect: 'انتخاب پالت گرادیان',
    fxReset: 'حالت پیش‌فرض این افکت',
    brightness: 'روشنایی',
    contrast: 'کنتراست',
    blur: 'بلور',
    grayscale: 'سیاه‌وسفید',
    aspectRatio: 'نسبت ابعاد',
    addLayer: 'افزودن متن جدید',
    addSticker: 'افزودن استیکر/عکس',
    addLabel: 'افزودن لیبل',
    tabAssets: 'لیبل‌ها',
    magicIntroTitle: 'استودیو جادویی تایپوگرافی',
    magicIntroDesc: 'ابزارهای هوشمند جلوه‌بخشی: خمیدگی و انحنای متن، سایه عمیق کشیده (Long Shadow)، ماسک تصویری، کشیدگی کلمات و انیمیشن‌های زنده.',
    templatesIntroTitle: 'قالب‌های شخصی و ذخیره‌شده',
    templatesIntroDesc: 'استایلی که الان تنظیم کردی رو می‌تونی ذخیره کنی تا دفعه بعد با یک کلیک راحت انتخابش کنی و استفاده کنی.',
    saveAsTemplate: 'ذخیره به عنوان قالب',
    lblCatAll: 'همه لیبل‌ها',
    lblCatSale: 'تخفیف و فروش',
    lblCatBadges: 'بج و استوری',
    lblCatShapes: 'فرم‌ها و کادر',
    labelOffBadge: 'تخفیف درصدی / OFF',
    labelSaleBadge: 'حراج داغ 🔥',
    labelSpecialOffer: 'پیشنهاد شگفت‌انگیز',
    labelNewBadge: 'محصول جدید / NEW',
    labelVerified: 'تضمین اصالت / تیک',
    labelStoryTag: 'استوری ترند',
    labelSwipeUp: 'ورق بزنید 👈',
    labelAssets: 'لیبل‌های آماده',
    labelAssetsHint: 'یک لیبل انتخاب کن؛ متن و رنگش بعداً قابل تغییر است.',
    labelPriceTag: 'تگ قیمت',
    labelStarburst: 'نشان تخفیف',
    labelRibbon: 'روبان',
    labelPill: 'کپسولی',
    labelTicket: 'بلیط',
    labelCircle: 'دایره',
    labelBanner: 'بنر',
    labelSpeech: 'حباب گفتگو',
    labelFlag: 'پرچم',
    newLabelText: 'تخفیف ویژه',
    editLabelText: 'متن لیبل را ویرایش کن',
    editSelectedLabel: 'ویرایش لیبل انتخاب‌شده',
    labelColor: 'رنگ لیبل',
    labelTextColor: 'رنگ متن',
    labelFont: 'فونت لیبل',
    labelTextHorizontal: 'جابه‌جایی متن افقی',
    labelTextVertical: 'جابه‌جایی متن عمودی',
    editingSelectedText: 'ویرایش لایهٔ متن انتخاب‌شده',
    editLayerText: 'متن این لایه را ویرایش کن',
    duplicateLayer: 'کپی این لایه',
    bringForward: 'بیار جلو',
    sendBackward: 'ببر عقب',
    deleteLayer: 'حذف لایه',
    newLayerText: 'متن جدید',
    bold: 'بولد',
    italic: 'ایتالیک',
    underline: 'زیرخط',
    shadow: 'سایه',
    stroke: 'دورخط',
    myImage: 'عکس من',
    uploadImage: 'آپلود عکس',
    size: 'اندازه',
    letterSpacing: 'فاصله حروف',
    lineHeight: 'فاصله خطوط',
    strokeWidth: 'ضخامت دورخط',
    opacity: 'شفافیت متن',
    margin: 'حاشیه',
    align_right: 'راست',
    align_center: 'وسط',
    align_left: 'چپ',
    exportingImage: 'در حال تولید و ذخیره تصویر باکیفیت…',
    copyingImage: 'در حال آماده‌سازی و کپی در کلیپ‌بورد…',
    clipboardFallbackDownload: 'به دلیل محدودیت کلیپ‌بورد در این محیط، تصویر مستقیم ذخیره شد.',
    saveToDevice: 'ذخیره در گالری دستگاه (PNG)',
    copyImageBtn: 'کپی عکس در کلیپ‌بورد',
    copyTextBtn: 'کپی متن',
    saveToAppGallery: 'ذخیره در گالری برنامه',
    myGallery: 'گالری من',
    emptyGallery: 'چیزی ذخیره نشده. یک متن بساز و ذخیره کن.',
    enableBg: 'طراحی پست و استوری (پس‌زمینه)',
    bgTabHelp: 'برای طراحی پست و استوری کامل؛ در صورت خاموش بودن، خروجی بدون پس‌زمینه (شفاف) ذخیره می‌شود.',
    resetBgSettings: 'بازنشانی تنظیمات پس‌زمینه',
    bgResetSuccess: 'تنظیمات پس‌زمینه به حالت اولیه بازنشانی شد.',
    donateText:
      'تمام مبالغی که حمایت مالی می‌شن صرف خرید فونت‌های جدید با لایسنس می‌شه تا رایگان و در دسترس همه توی FontWoW قرار بگیرن.',
    fontIranLogoAlt: 'لوگوی فونت‌ایران',
    fontIranSupportTitle: 'با حمایت فونت‌ایران',
    fontIranSupportText: 'بنیان‌گذار فونت‌ایران برای خرید همهٔ فونت‌های این فهرست ۲۰٪ تخفیف در نظر گرفته است.',
    discount: 'تخفیف',
    toman: 'تومان',
    unlimited: 'نامحدود',
    of: 'از',
    payViaZibal: 'پرداخت تومانی',
    payViaCrypto: 'پرداخت با کریپتو',
    donateNotSet: 'لینک درگاه هنوز تنظیم نشده.',
    suggestFontLabel: 'دوست داری چه فونتی اضافه بشه؟',
    suggestFontPlaceholder: 'اسم فونت مورد نظرت رو بنویس…',
    sendSuggestion: 'ارسال پیشنهاد فونت',
    themeColor: 'رنگ تم برنامه',
    stageGradient: 'گرادیانت پس‌زمینه محیط کار (استیج)',
    language: 'زبان',
    contact: 'ارتباط با ما',
    version: 'نسخه',
    whatsNew: 'آخرین تغییرات',
    updateAvailable: 'نسخه‌ی جدید در دسترسه',
    updateDownload: 'دانلود آپدیت',
    shareKitLink: 'پک رسانه‌ای و اشتراک‌گذاری',
    shareKitTitle: 'پک رسانه‌ای و اشتراک‌گذاری FontWoW',
    shareKitDesc: 'با فونت‌واو (FontWoW) متن‌های استوری خیره‌کننده بساز و با دوستان و دیگر طراحان به اشتراک بگذار!',
    downloadPromo: 'دانلود تصویر با کیفیت بالا',
    promoStoryTab: 'استوری اینستاگرام (۹:۱۶)',
    promoPostTab: 'پست اینستاگرام (۱:۱)',
    copyPromoText: 'کپی متن معرفی برنامه',
    promoCopiedToast: 'متن معرفی کپی شد!',
    projectLink: 'لینک پروژه',
    featuresTitle: 'امکانات و قابلیت‌های کلیدی',
    downloadAppTitle: 'دانلود نرم‌افزار از مارکت‌های مختلف',
    downloadApk: 'دانلود مستقیم APK (اندروید)',
    downloadBazaar: 'دریافت از کافه بازار',
    downloadMyket: 'دریافت از مایکت',
    downloadWebApp: 'اجرای نسخه تحت وب (PWA)',
    resetSettings: 'بازگردانی تنظیمات',
    openSource: 'متن‌باز روی گیت‌هاب',
    fontAdded: 'فونت اضافه شد',
    fontError: 'خطا در بارگذاری فونت',
    fontRenamed: 'نام فونت تغییر کرد',
    renameFontPrompt: 'نام جدید فونت را وارد کن',
    bgAdded: 'پس‌زمینه اضافه شد',
    bgError: 'خطا در بارگذاری عکس',
    imageSaved: 'عکس ذخیره شد',
    imageError: 'خطا در ساخت عکس',
    imageCopied: 'عکس در کلیپ‌بورد کپی شد',
    imageShared: 'کلیپ‌بورد در دسترس نبود؛ عکس برای اشتراک‌گذاری باز شد',
    imageCopyFallback: 'کپی عکس پشتیبانی نشد؛ متن کپی شد',
    copyFailed: 'کپی ناموفق بود',
    textCopied: 'متن کپی شد',
    writeFirst: 'اول یک متن بنویس',
    savedToGallery: 'در گالری ذخیره شد',
    versionAdded: 'نسخه جدید ذخیره شد',
    versions: 'نسخه',
    saveNewVersion: 'ذخیره به‌عنوان نسخه جدید',
    loadLatest: 'آخرین نسخه',
    newStyle: 'استایل جدید',
    styleStudio: 'استودیوی استایل',
    styleStudioHint:
      'فونت، رنگ، جعبه، پس‌زمینه و افکتی که الان روی صفحه انتخاب کردی، به‌عنوان یک استایل ذخیره می‌شه.',
    styleNameLabel: 'اسم استایل',
    styleNamePlaceholder: 'مثلاً: عصر جمعه',
    saveStyleToApp: 'ذخیره در برنامه',
    copyStyleJSON: 'کپی JSON برای افزودن دائمی',
    styleSaved: 'استایل ذخیره شد',
    styleJSONCopied: 'JSON استایل کپی شد؛ توی src/templates.json بچسبونش',
    nameFirst: 'اول یک اسم برای استایل بنویس',
    deleteStyle: 'حذف استایل',
    styleStudioJsonHint:
      'برای اضافه کردن دائمی این استایل به پروژه، این JSON رو کپی کن و به آرایه‌ی داخل src/templates.json اضافه کن.',
    fontLicenses: 'لایسنس فونت‌ها',
    fontLicensesText:
      'تمام فونت‌های موجود در FontWoW از Google Fonts هستن و تحت لایسنس‌های متن‌باز (بیشتر SIL Open Font License، Roboto تحت Apache License 2.0) در اختیار طراح‌هاشون منتشر شدن. حق مالکیت هر فونت متعلق به طراح اصلی‌شه.',
    copyCss: 'کپی CSS',
    downloadCss: 'دانلود CSS',
    copyHtml: 'کپی HTML',
    preview: 'پیشنمایش',
    htmlElement: 'عنصر HTML',
    cssCopied: 'CSS کپی شد',
    htmlCopied: 'HTML کپی شد',
    searchGoogleFonts: 'جستجوی فونت‌های گوگل...',
    addGoogleFont: 'جستجو و افزودن فونت گوگل',
    searchFontsPlaceholder: 'نام فونت را بنویسید (مثلا: Estedad, Inter...)',
    noFontsFound: 'فونتی پیدا نشد',
    alreadyAdded: 'این فونت قبلاً اضافه شده است',
    loadingFont: 'درحال بارگذاری فونت...',
    startupLoading: 'در حال آماده‌سازی بوم',
    diagnosticsTitle: 'عیب‌یابی و وضعیت سیستم',
    systemStatus: 'وضعیت سیستم',
    systemHealthy: 'همه بخش‌ها در وضعیت مطلوب هستند.',
    systemWarnings: 'برخی هشدارها در سیستم وجود دارد.',
    systemErrors: 'مشکلات جدی در سیستم شناسایی شده است!',
    runAutoFix: 'رفع خودکار مشکلات',
    copyLogs: 'کپی لاگ‌ها',
    clearLogs: 'پاک کردن لاگ‌ها',
    logsList: 'لیست رویدادها (لاگ‌ها)',
    allLogs: 'همه لاگ‌ها',
    infoLogs: 'اطلاعات',
    warnLogs: 'هشدارها',
    errorLogs: 'خطاها',
    preflightWarning: 'بررسی پیش از عملیات...',
    preflightFixed: 'مشکلات سیستم با موفقیت برطرف شد و عملیات ادامه می‌یابد.',
    preflightErrorPrompt: 'خطایی شناسایی شد. آیا می‌خواهید سیستم آن را خودکار رفع کند؟',
    fixSuccess: 'عیب‌یابی با موفقیت انجام شد و مشکلات برطرف شدند.',
    searchLogsPlaceholder: 'جستجو در لاگ‌ها...',
    noLogs: 'هیچ لاگی ثبت نشده است.',
    storageUsage: 'میزان استفاده از حافظه مرورگر',
    browserCapabilities: 'سازگاری مرورگر',
    networkStatus: 'وضعیت شبکه',
    customFontsStatus: 'وضعیت فونت‌های سفارشی',
    localStorageStatus: 'وضعیت ذخیره‌ساز محلی',
    magicLayout: 'چیدمان جادویی بعدی',
    magicLayoutApplied: 'یک چیدمان تازه اعمال شد',
    warpText: 'متن روی مسیر',
    warp_none: 'ساده',
    warp_arc: 'قوس',
    warp_wave: 'موج',
    warp_circle: 'دایره',
    warpBend: 'شدت خمیدگی',
    longShadow: 'سایهٔ سه‌بعدی',
    shadowDepth: 'عمق سایه',
    shadowAngle: 'زاویهٔ سایه',
    shadowColor: 'رنگ سایه',
    textMask: 'تصویر داخل متن',
    chooseMaskImage: 'انتخاب تصویر ماسک',
    removeMask: 'حذف ماسک',
    textMaskAdded: 'تصویر داخل متن قرار گرفت',
    smartKashida: 'کشیدهٔ هوشمند فارسی',
    kashidaAmount: 'مقدار کشیده',
    removeBackground: 'حذف پس‌زمینهٔ استیکر',
    removeSelectedBackground: 'حذف پس‌زمینهٔ عکس انتخاب‌شده',
    removeBackgroundHint: 'برای بهترین نتیجه، عکسی با پس‌زمینهٔ ساده و یکدست انتخاب کنید.',
    backgroundRemoved: 'پس‌زمینهٔ عکس حذف شد',
    backgroundRemoveFailed: 'حذف پس‌زمینه ناموفق بود',
    animation: 'انیمیشن خروجی',
    animation_rise: 'ورود از پایین',
    animation_fade: 'محو شدن',
    animation_zoom: 'بزرگ‌نمایی',
    animation_type: 'تایپ',
    saveAnimatedGif: 'ذخیرهٔ خروجی متحرک (GIF)',
    gifExporting: 'در حال ساخت GIF…',
    gifSaved: 'خروجی متحرک آماده شد',
    gifError: 'ساخت خروجی متحرک ناموفق بود',
    saveAnimatedVideo: 'ذخیرهٔ ویدئوی متحرک (WebM)',
    videoExporting: 'در حال ساخت ویدئو…',
    videoSaved: 'ویدئوی متحرک آماده شد',
    videoError: 'ساخت ویدئو ناموفق بود',
    videoUnsupported: 'مرورگر شما از خروجی ویدئو پشتیبانی نمی‌کند',
  },
  en: {
    save: 'Save',
    gallery: 'Gallery',
    donate: 'Support',
    settings: 'Settings',
    undo: 'Undo',
    redo: 'Redo',
    placeholder: 'Type here…',
    clear: 'Clear',
    tabFont: 'Font',
    tabStyle: 'Style',
    tabBox: 'Text Box',
    boxCustomize: 'Customize Text Box',
    boxBgColor: 'Box Background Color',
    boxOpacity: 'Box Opacity',
    boxRadius: 'Corner Radius',
    boxPadding: 'Inner Padding',
    boxReset: 'Reset to Style Default',
    tabColor: 'Color',
    tabBg: 'Background',
    tabLayout: 'Layout',
    tabMagic: 'Magic',
    tabTemplates: 'Templates',
    yourFont: 'Your Font',
    effect: 'Text Effect & Style',
    fx_none: 'Clean / None',
    fx_neon: 'Cyber Neon',
    fx_gradient: 'Vibrant Gradient',
    fx_pop3d: '3D Pop Extruded',
    fx_glitch: 'Cyber Glitch',
    fx_retro: 'Retro Pop-Art',
    fx_softBloom: 'Dreamy Bloom',
    fx_emboss: 'Embossed 3D',
    fx_glass: 'Liquid Glass',
    fx_outline: 'Hollow Outline',
    fx_fire: 'Fire & Blaze',
    fx_duoStroke: 'Duo Contour',
    fx_chrome: 'Gold Chrome',
    fx_shadowCast: 'Cinematic Shadow',
    fxCustomize: 'Effect Customizer',
    fxColor: 'Effect / Aura Color',
    fxGradientSelect: 'Gradient Palette',
    fxReset: 'Reset to Effect Default',
    brightness: 'Brightness',
    contrast: 'Contrast',
    blur: 'Blur',
    grayscale: 'Grayscale',
    aspectRatio: 'Aspect Ratio',
    addLayer: 'Add text layer',
    addSticker: 'Add sticker or image',
    addLabel: 'Add label',
    tabAssets: 'Labels',
    magicIntroTitle: 'Magic Typography Studio',
    magicIntroDesc: 'Smart design tools: text warp & arching, 3D long shadows, image clipping masks, smart kashida and motion animations.',
    templatesIntroTitle: 'Saved Styles & Presets',
    templatesIntroDesc: 'Save your current text styling as a template to easily reuse it anytime with a single tap.',
    saveAsTemplate: 'Save as Template',
    lblCatAll: 'All Labels',
    lblCatSale: 'Sale & Offers',
    lblCatBadges: 'Badges & Stories',
    lblCatShapes: 'Shapes & Frames',
    labelOffBadge: 'Discount / OFF Badge',
    labelSaleBadge: 'Hot Sale 🔥',
    labelSpecialOffer: 'Special Offer',
    labelNewBadge: 'New Arrival / NEW',
    labelVerified: 'Verified / Quality',
    labelStoryTag: 'Story Tag',
    labelSwipeUp: 'Swipe Up 👈',
    labelAssets: 'Ready-made labels',
    labelAssetsHint: 'Pick a label, then customize its text and colors.',
    labelPriceTag: 'Price tag',
    labelStarburst: 'Sale badge',
    labelRibbon: 'Ribbon',
    labelPill: 'Pill',
    labelTicket: 'Ticket',
    labelCircle: 'Circle',
    labelBanner: 'Banner',
    labelSpeech: 'Speech bubble',
    labelFlag: 'Flag',
    newLabelText: 'Special offer',
    editLabelText: 'Edit label text',
    editSelectedLabel: 'Edit selected label',
    labelColor: 'Label color',
    labelTextColor: 'Text color',
    labelFont: 'Label font',
    labelTextHorizontal: 'Text horizontal position',
    labelTextVertical: 'Text vertical position',
    editingSelectedText: 'Editing selected text layer',
    editLayerText: "Edit this layer's text",
    duplicateLayer: 'Duplicate this layer',
    bringForward: 'Bring forward',
    sendBackward: 'Send backward',
    deleteLayer: 'Delete layer',
    newLayerText: 'New text',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    shadow: 'Shadow',
    stroke: 'Outline',
    myImage: 'My Image',
    uploadImage: 'Upload Image',
    size: 'Size',
    letterSpacing: 'Letter Spacing',
    lineHeight: 'Line Height',
    strokeWidth: 'Outline Width',
    opacity: 'Opacity',
    margin: 'Margin',
    align_right: 'Right',
    align_center: 'Center',
    align_left: 'Left',
    exportingImage: 'Generating high-quality image…',
    copyingImage: 'Preparing and copying to clipboard…',
    clipboardFallbackDownload: 'Due to browser clipboard restrictions, image was downloaded directly.',
    saveToDevice: 'Save to device gallery (PNG)',
    copyImageBtn: 'Copy image to clipboard',
    copyTextBtn: 'Copy text',
    saveToAppGallery: 'Save to app gallery',
    myGallery: 'My Gallery',
    emptyGallery: 'Nothing saved yet. Create something and save it.',
    enableBg: 'Post & Story Design (Background)',
    bgTabHelp: 'Design complete posts & stories; when disabled, export is saved transparent.',
    resetBgSettings: 'Reset Background Settings',
    bgResetSuccess: 'Background settings reset to default.',
    donateText:
      'Every donation goes toward buying licensed fonts, added to FontWoW for free and available to everyone.',
    fontIranLogoAlt: 'FontIran logo',
    fontIranSupportTitle: 'Supported by FontIran',
    fontIranSupportText: 'FontIran’s founder has offered FontWoW 20% off every font on this list.',
    discount: 'off',
    toman: 'toman',
    unlimited: 'Unlimited',
    of: 'of',
    payViaZibal: 'Toman Payment',
    payViaCrypto: 'Pay with crypto',
    donateNotSet: 'Payment link is not set yet.',
    suggestFontLabel: 'Which font would you like added?',
    suggestFontPlaceholder: 'Type the font name…',
    sendSuggestion: 'Send font suggestion',
    themeColor: 'App Theme Color',
    stageGradient: 'Stage Background Gradient',
    language: 'Language',
    contact: 'Contact Us',
    version: 'Version',
    whatsNew: "What's New",
    updateAvailable: 'A new version is available',
    updateDownload: 'Download update',
    shareKitLink: 'Media Kit & Sharing',
    shareKitTitle: 'FontWoW Media Kit & Sharing',
    shareKitDesc: 'Create stunning story texts with FontWoW and share them with your friends and other designers!',
    downloadPromo: 'Download High-Quality Image',
    promoStoryTab: 'Instagram Story (9:16)',
    promoPostTab: 'Instagram Post (1:1)',
    copyPromoText: 'Copy Share Text',
    promoCopiedToast: 'Share text copied to clipboard!',
    projectLink: 'Project Link',
    featuresTitle: 'Key Features & Options',
    downloadAppTitle: 'Download App on Various Sites',
    downloadApk: 'Direct APK Download (Android)',
    downloadBazaar: 'Get on Cafe Bazaar',
    downloadMyket: 'Get on Myket',
    downloadWebApp: 'Open Web App (PWA)',
    resetSettings: 'Reset Settings',
    openSource: 'Open source on GitHub',
    fontAdded: 'Font added',
    fontError: 'Failed to load font',
    fontRenamed: 'Font renamed',
    renameFontPrompt: 'Enter a new name for the font',
    bgAdded: 'Background added',
    bgError: 'Failed to load image',
    imageSaved: 'Image saved',
    imageError: 'Failed to create image',
    imageCopied: 'Image copied to clipboard',
    imageShared: 'Clipboard unavailable; opened the share sheet instead',
    imageCopyFallback: 'Image copy not supported; text copied instead',
    copyFailed: 'Copy failed',
    textCopied: 'Text copied',
    writeFirst: 'Write some text first',
    savedToGallery: 'Saved to gallery',
    versionAdded: 'New version saved',
    versions: 'Versions',
    saveNewVersion: 'Save as new version',
    loadLatest: 'Latest version',
    newStyle: 'New Style',
    styleStudio: 'Style Studio',
    styleStudioHint:
      'The font, color, box, background, and effect currently selected on the canvas will be saved as one style.',
    styleNameLabel: 'Style name',
    styleNamePlaceholder: 'e.g. Friday Evening',
    saveStyleToApp: 'Save in app',
    copyStyleJSON: 'Copy JSON to add permanently',
    styleSaved: 'Style saved',
    styleJSONCopied: 'Style JSON copied; paste it into src/templates.json',
    nameFirst: 'Give your style a name first',
    deleteStyle: 'Delete style',
    styleStudioJsonHint:
      'To add this style to the project permanently, copy this JSON and add it to the array in src/templates.json.',
    fontLicenses: 'Font Licenses',
    fontLicensesText:
      'Every font in FontWoW is served by Google Fonts under open licenses (mostly the SIL Open Font License; Roboto under Apache License 2.0), published by their original designers. Copyright for each font belongs to its designer.',
    copyCss: 'Copy CSS',
    downloadCss: 'Download CSS',
    copyHtml: 'Copy HTML',
    preview: 'Preview',
    htmlElement: 'HTML Element',
    cssCopied: 'CSS copied!',
    htmlCopied: 'HTML copied!',
    searchGoogleFonts: 'Search Google Fonts...',
    addGoogleFont: 'Search & Add Google Font',
    searchFontsPlaceholder: 'Type font name (e.g. Estedad, Inter...)',
    noFontsFound: 'No fonts found',
    alreadyAdded: 'This font is already added',
    loadingFont: 'Loading font...',
    startupLoading: 'Preparing your canvas',
    diagnosticsTitle: 'Diagnostics & System Status',
    systemStatus: 'System Status',
    systemHealthy: 'All systems are operating normally.',
    systemWarnings: 'Some warnings have been detected.',
    systemErrors: 'Critical issues detected in the system!',
    runAutoFix: 'Auto-Fix Issues',
    copyLogs: 'Copy Logs',
    clearLogs: 'Clear Logs',
    logsList: 'Event Logs',
    allLogs: 'All Logs',
    infoLogs: 'Info',
    warnLogs: 'Warnings',
    errorLogs: 'Errors',
    preflightWarning: 'Pre-flight check in progress...',
    preflightFixed: 'System issues resolved successfully. Proceeding...',
    preflightErrorPrompt: 'Issues detected. Run auto-fix before proceeding?',
    fixSuccess: 'Diagnostics run complete. Issues fixed successfully.',
    searchLogsPlaceholder: 'Search logs...',
    noLogs: 'No logs recorded.',
    storageUsage: 'LocalStorage Usage',
    browserCapabilities: 'Browser Compatibility',
    networkStatus: 'Network Status',
    customFontsStatus: 'Custom Fonts Status',
    localStorageStatus: 'LocalStorage Status',
    magicLayout: 'Try the next magic layout',
    magicLayoutApplied: 'A fresh layout was applied',
    warpText: 'Text on a Path',
    warp_none: 'Straight',
    warp_arc: 'Arc',
    warp_wave: 'Wave',
    warp_circle: 'Circle',
    warpBend: 'Curve Strength',
    longShadow: '3D Long Shadow',
    shadowDepth: 'Shadow Depth',
    shadowAngle: 'Shadow Angle',
    shadowColor: 'Shadow Color',
    textMask: 'Image Inside Text',
    chooseMaskImage: 'Choose Mask Image',
    removeMask: 'Remove Mask',
    textMaskAdded: 'Image placed inside the text',
    smartKashida: 'Smart Persian Kashida',
    kashidaAmount: 'Kashida Amount',
    removeBackground: 'Sticker Background Remover',
    removeSelectedBackground: 'Remove selected image background',
    removeBackgroundHint: 'For best results, choose an image with a simple, solid background.',
    backgroundRemoved: 'Image background removed',
    backgroundRemoveFailed: 'Could not remove the background',
    animation: 'Export Animation',
    animation_rise: 'Rise',
    animation_fade: 'Fade',
    animation_zoom: 'Zoom',
    animation_type: 'Type',
    saveAnimatedGif: 'Save animated GIF',
    gifExporting: 'Creating GIF…',
    gifSaved: 'Animated export is ready',
    gifError: 'Could not create animated export',
    saveAnimatedVideo: 'Save animated video (WebM)',
    videoExporting: 'Creating video…',
    videoSaved: 'Animated video is ready',
    videoError: 'Could not create the video',
    videoUnsupported: 'Your browser does not support video export',
  },
}
